# Source: enbuild/templates/enbuild-bolt.yaml
apiVersion: v1
kind: Service
metadata:
  name: enbuild-enbuild-bolt
  labels:
    app: bolt
    app.kubernetes.io/component: bolt
    helm.sh/chart: enbuild-0.0.25
    app.kubernetes.io/name: enbuild
    app.kubernetes.io/instance: enbuild
    app.kubernetes.io/version: "1.0.20"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  selector:
    app: bolt
    app.kubernetes.io/component: bolt
    app.kubernetes.io/name: enbuild
    app.kubernetes.io/instance: enbuild
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5173
---
# Source: enbuild/templates/enbuild-bolt.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enbuild-enbuild-bolt
  labels:
    app: bolt
    app.kubernetes.io/component: bolt
    helm.sh/chart: enbuild-0.0.25
    app.kubernetes.io/name: enbuild
    app.kubernetes.io/instance: enbuild
    app.kubernetes.io/version: "1.0.20"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bolt
      app.kubernetes.io/component: bolt
      app.kubernetes.io/name: enbuild
      app.kubernetes.io/instance: enbuild
  template:
    metadata:
      labels:
        app: bolt
        app.kubernetes.io/component: bolt
        app.kubernetes.io/name: enbuild
        app.kubernetes.io/instance: enbuild
    spec:
      containers:
        - env:
            - name: MAX_CONTEXT_LENGTH
              value: "1000"
            - name: NODE_ENV
              value: "production"
            - name: COMPOSE_PROFILES
              value: "production"
            - name: VITE_BASE_PATH
              value: "bolt"
            - name: VITE_SERVER_ALLOWED_HOSTS
              value: "lightning.vivplatform.io"
            - name: PORT
              value: "5173"
            - name: DEFAULT_NUM_CTX
              value: "32768"
            - name: RUNNING_IN_DOCKER
              value: "true"
            - name: AWS_BEDROCK_CONFIG
              value: '{"region": "us-east-1"}'
            - name: AUTH_API_URL
              value: "http://enbuild-enbuild-user/api/v1/roles/auth"
            - name: OLLAMA_API_BASE_URL
              value: "http://open-webui-ollama.dev-enbuild.svc.cluster.local:11434"
          envFrom:
            - secretRef:
                name: enbuild-mongo-secrets
            - secretRef:
                name: enbuild-backend-secret
          imagePullPolicy: Always
          image: ghcr.io/junaid18183/bolt.diy:latest
          name: enbuild-bolt
          ports:
            - containerPort: 5173
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
---

